namespace TdB_Odyssee.UserControlLibrary
{
    partial class ucAdminPriorties
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.ConditionalFormattingObject conditionalFormattingObject1 = new Telerik.WinControls.UI.ConditionalFormattingObject();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            this.rgvVague = new Telerik.WinControls.UI.RadGridView();
            this.tDBPRIORITEBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.dsTdbOdyssee = new TdB_Odyssee.Dal.dsTdbOdyssee();
            this.tDB_PRIORITETableAdapter = new TdB_Odyssee.Dal.dsTdbOdysseeTableAdapters.TDB_PRIORITETableAdapter();
            this.office2010BlackTheme1 = new Telerik.WinControls.Themes.Office2010BlackTheme();
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tDBPRIORITEBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dsTdbOdyssee)).BeginInit();
            this.SuspendLayout();
            // 
            // rgvVague
            // 
            this.rgvVague.BackColor = System.Drawing.Color.Transparent;
            this.rgvVague.BackgroundImage = global::TdB_Odyssee.Properties.Resources.FOND;
            this.rgvVague.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rgvVague.Cursor = System.Windows.Forms.Cursors.Default;
            this.rgvVague.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rgvVague.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.rgvVague.ForeColor = System.Drawing.SystemColors.ControlText;
            this.rgvVague.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.rgvVague.Location = new System.Drawing.Point(0, 0);
            // 
            // rgvVague
            // 
            this.rgvVague.MasterTemplate.AutoGenerateColumns = false;
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "ID_PRIORITE";
            gridViewDecimalColumn1.HeaderText = "ID_PRIORITE";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "ID_PRIORITE";
            gridViewDecimalColumn1.ReadOnly = true;
            conditionalFormattingObject1.ApplyToRow = true;
            conditionalFormattingObject1.CellBackColor = System.Drawing.Color.Empty;
            conditionalFormattingObject1.CellForeColor = System.Drawing.Color.Empty;
            conditionalFormattingObject1.ConditionType = Telerik.WinControls.UI.ConditionTypes.NotEqual;
            conditionalFormattingObject1.Name = "lineColor";
            conditionalFormattingObject1.RowBackColor = System.Drawing.Color.Beige;
            conditionalFormattingObject1.RowForeColor = System.Drawing.Color.Empty;
            conditionalFormattingObject1.TValue1 = "-1";
            gridViewTextBoxColumn1.ConditionalFormattingObjectList.Add(conditionalFormattingObject1);
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "NOM_PRIORITE";
            gridViewTextBoxColumn1.HeaderText = "NOM_PRIORITE";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "NOM_PRIORITE";
            gridViewTextBoxColumn1.Width = 300;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "DESCRIPTION_PRIORITE";
            gridViewTextBoxColumn2.HeaderText = "DESCRIPTION_PRIORITE";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "DESCRIPTION_PRIORITE";
            gridViewTextBoxColumn2.Width = 500;
            this.rgvVague.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewTextBoxColumn1,
            gridViewTextBoxColumn2});
            this.rgvVague.MasterTemplate.DataSource = this.tDBPRIORITEBindingSource;
            this.rgvVague.MasterTemplate.EnableFiltering = true;
            this.rgvVague.Name = "rgvVague";
            this.rgvVague.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.rgvVague.Size = new System.Drawing.Size(1008, 554);
            this.rgvVague.TabIndex = 2;
            this.rgvVague.Text = "radGridView1";
            this.rgvVague.ThemeName = "Office2010Black";
            this.rgvVague.UserAddedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.MasterTemplate_UserAddedRow);
            this.rgvVague.UserDeletingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.MasterTemplate_UserDeletingRow);
            this.rgvVague.CellValueChanged += new Telerik.WinControls.UI.GridViewCellEventHandler(this.MasterTemplate_CellValueChanged);
            // 
            // tDBPRIORITEBindingSource
            // 
            this.tDBPRIORITEBindingSource.DataMember = "TDB_PRIORITE";
            this.tDBPRIORITEBindingSource.DataSource = this.dsTdbOdyssee;
            // 
            // dsTdbOdyssee
            // 
            this.dsTdbOdyssee.DataSetName = "dsTdbOdyssee";
            this.dsTdbOdyssee.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // tDB_PRIORITETableAdapter
            // 
            this.tDB_PRIORITETableAdapter.ClearBeforeFill = true;
            // 
            // ucAdminPriorties
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::TdB_Odyssee.Properties.Resources.FOND;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Controls.Add(this.rgvVague);
            this.DoubleBuffered = true;
            this.Name = "ucAdminPriorties";
            this.Size = new System.Drawing.Size(1008, 554);
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tDBPRIORITEBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dsTdbOdyssee)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private Telerik.WinControls.UI.RadGridView rgvVague;
        private System.Windows.Forms.BindingSource tDBPRIORITEBindingSource;
        private Dal.dsTdbOdyssee dsTdbOdyssee;
        private Dal.dsTdbOdysseeTableAdapters.TDB_PRIORITETableAdapter tDB_PRIORITETableAdapter;
        private Telerik.WinControls.Themes.Office2010BlackTheme office2010BlackTheme1;
    }
}
