namespace TdB_Odyssee.UserControlLibrary
{
    partial class ucAdminVague
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            Telerik.WinControls.UI.GridViewDecimalColumn gridViewDecimalColumn1 = new Telerik.WinControls.UI.GridViewDecimalColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn1 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.ConditionalFormattingObject conditionalFormattingObject1 = new Telerik.WinControls.UI.ConditionalFormattingObject();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn1 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            Telerik.WinControls.UI.GridViewDateTimeColumn gridViewDateTimeColumn2 = new Telerik.WinControls.UI.GridViewDateTimeColumn();
            Telerik.WinControls.UI.GridViewTextBoxColumn gridViewTextBoxColumn2 = new Telerik.WinControls.UI.GridViewTextBoxColumn();
            this.rgvVague = new Telerik.WinControls.UI.RadGridView();
            this.tDBVAGUEBindingSource = new System.Windows.Forms.BindingSource(this.components);
            this.dsTdbOdyssee = new TdB_Odyssee.Dal.dsTdbOdyssee();
            this.FolderBrowserDialog = new System.Windows.Forms.FolderBrowserDialog();
            this.office2010BlackTheme1 = new Telerik.WinControls.Themes.Office2010BlackTheme();
            this.tDB_VAGUETableAdapter = new TdB_Odyssee.Dal.dsTdbOdysseeTableAdapters.TDB_VAGUETableAdapter();
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague.MasterTemplate)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.tDBVAGUEBindingSource)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dsTdbOdyssee)).BeginInit();
            this.SuspendLayout();
            // 
            // rgvVague
            // 
            this.rgvVague.BackColor = System.Drawing.Color.Transparent;
            this.rgvVague.BackgroundImage = global::TdB_Odyssee.Properties.Resources.FOND;
            this.rgvVague.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.rgvVague.Cursor = System.Windows.Forms.Cursors.Default;
            this.rgvVague.Dock = System.Windows.Forms.DockStyle.Fill;
            this.rgvVague.Font = new System.Drawing.Font("Segoe UI", 8.25F);
            this.rgvVague.ForeColor = System.Drawing.SystemColors.ControlText;
            this.rgvVague.ImeMode = System.Windows.Forms.ImeMode.NoControl;
            this.rgvVague.Location = new System.Drawing.Point(0, 0);
            // 
            // rgvVague
            // 
            gridViewDecimalColumn1.DataType = typeof(int);
            gridViewDecimalColumn1.EnableExpressionEditor = false;
            gridViewDecimalColumn1.FieldName = "ID_VAGUE";
            gridViewDecimalColumn1.HeaderText = "ID_VAGUE";
            gridViewDecimalColumn1.IsAutoGenerated = true;
            gridViewDecimalColumn1.IsVisible = false;
            gridViewDecimalColumn1.Name = "ID_VAGUE";
            gridViewDecimalColumn1.ReadOnly = true;
            conditionalFormattingObject1.ApplyToRow = true;
            conditionalFormattingObject1.CellBackColor = System.Drawing.Color.Empty;
            conditionalFormattingObject1.CellForeColor = System.Drawing.Color.Empty;
            conditionalFormattingObject1.ConditionType = Telerik.WinControls.UI.ConditionTypes.NotEqual;
            conditionalFormattingObject1.Name = "lineColor";
            conditionalFormattingObject1.RowBackColor = System.Drawing.Color.Beige;
            conditionalFormattingObject1.RowForeColor = System.Drawing.Color.Empty;
            conditionalFormattingObject1.TValue1 = "-1";
            gridViewDateTimeColumn1.ConditionalFormattingObjectList.Add(conditionalFormattingObject1);
            gridViewDateTimeColumn1.EnableExpressionEditor = false;
            gridViewDateTimeColumn1.FieldName = "DATE_VAGUE";
            gridViewDateTimeColumn1.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            gridViewDateTimeColumn1.HeaderText = "Date de la Vague";
            gridViewDateTimeColumn1.Name = "dtpDateVague";
            gridViewDateTimeColumn1.Width = 150;
            gridViewTextBoxColumn1.EnableExpressionEditor = false;
            gridViewTextBoxColumn1.FieldName = "NOM_VAGUE";
            gridViewTextBoxColumn1.HeaderText = "Nom de la Vague";
            gridViewTextBoxColumn1.IsAutoGenerated = true;
            gridViewTextBoxColumn1.Name = "NOM_VAGUE";
            gridViewTextBoxColumn1.Width = 250;
            gridViewDateTimeColumn2.EnableExpressionEditor = false;
            gridViewDateTimeColumn2.FieldName = "DATE_VAGUE";
            gridViewDateTimeColumn2.Format = System.Windows.Forms.DateTimePickerFormat.Long;
            gridViewDateTimeColumn2.HeaderText = "DATE_VAGUE";
            gridViewDateTimeColumn2.IsAutoGenerated = true;
            gridViewDateTimeColumn2.IsVisible = false;
            gridViewDateTimeColumn2.Name = "DATE_VAGUE";
            gridViewDateTimeColumn2.Width = 102;
            gridViewTextBoxColumn2.EnableExpressionEditor = false;
            gridViewTextBoxColumn2.FieldName = "VAGUE_DESCRIPTION";
            gridViewTextBoxColumn2.HeaderText = "Description";
            gridViewTextBoxColumn2.IsAutoGenerated = true;
            gridViewTextBoxColumn2.Name = "Description";
            gridViewTextBoxColumn2.Width = 500;
            this.rgvVague.MasterTemplate.Columns.AddRange(new Telerik.WinControls.UI.GridViewDataColumn[] {
            gridViewDecimalColumn1,
            gridViewDateTimeColumn1,
            gridViewTextBoxColumn1,
            gridViewDateTimeColumn2,
            gridViewTextBoxColumn2});
            this.rgvVague.MasterTemplate.DataSource = this.tDBVAGUEBindingSource;
            this.rgvVague.Name = "rgvVague";
            this.rgvVague.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.rgvVague.Size = new System.Drawing.Size(1008, 554);
            this.rgvVague.TabIndex = 1;
            this.rgvVague.Text = "radGridView1";
            this.rgvVague.ThemeName = "Office2010Black";
            this.rgvVague.UserAddedRow += new Telerik.WinControls.UI.GridViewRowEventHandler(this.rgvVague_UserAddedRow);
            this.rgvVague.UserDeletingRow += new Telerik.WinControls.UI.GridViewRowCancelEventHandler(this.rgvVague_UserDeletingRow);
            this.rgvVague.CellValueChanged += new Telerik.WinControls.UI.GridViewCellEventHandler(this.rgvVague_CellValueChanged);
            // 
            // tDBVAGUEBindingSource
            // 
            this.tDBVAGUEBindingSource.DataMember = "TDB_VAGUE";
            this.tDBVAGUEBindingSource.DataSource = this.dsTdbOdyssee;
            // 
            // dsTdbOdyssee
            // 
            this.dsTdbOdyssee.DataSetName = "dsTdbOdyssee";
            this.dsTdbOdyssee.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            // 
            // tDB_VAGUETableAdapter
            // 
            this.tDB_VAGUETableAdapter.ClearBeforeFill = true;
            // 
            // ucAdminVague
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackgroundImage = global::TdB_Odyssee.Properties.Resources.FOND;
            this.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.Controls.Add(this.rgvVague);
            this.DoubleBuffered = true;
            this.Name = "ucAdminVague";
            this.Size = new System.Drawing.Size(1008, 554);
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague.MasterTemplate)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.rgvVague)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.tDBVAGUEBindingSource)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dsTdbOdyssee)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.FolderBrowserDialog FolderBrowserDialog;
        private Telerik.WinControls.UI.RadGridView rgvVague;
        private Dal.dsTdbOdyssee dsTdbOdyssee;
        private Telerik.WinControls.Themes.Office2010BlackTheme office2010BlackTheme1;
        private System.Windows.Forms.BindingSource tDBVAGUEBindingSource;
        private Dal.dsTdbOdysseeTableAdapters.TDB_VAGUETableAdapter tDB_VAGUETableAdapter;
    }
}
